version: '3'

services:

  front-backend1:
    container_name: my-apache-container
    build:
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - php-backend

  front-backend2:
    container_name: my-nginx-container
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php-backend

  php-backend:
    container_name: my-php-container
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql-database

  mysql-database:
    container_name: my-mysql-container
    build:
      context: ./mysql
      dockerfile: Dockerfile
